package com.bookstore.entity;
// Generated 25 Jan, 2020 4:13:21 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "boobkstore")
public class Customer implements java.io.Serializable {

	private Integer customerId;
	private String customerEmail;
	private String customerFullName;
	private String customerAddress;
	private String customerCity;
	private String customerCountry;
	private Date customerRegisterDate;
	private String customerPassword;
	private String customerPhone;
	private Integer customerZipCode;
	private Set<BookOrder> bookOrders = new HashSet<BookOrder>(0);

	public Customer() {
	}

	public Customer(String customerEmail, String customerFullName, String customerAddress, String customerCity,
			String customerCountry, Date customerRegisterDate, String customerPassword) {
		this.customerEmail = customerEmail;
		this.customerFullName = customerFullName;
		this.customerAddress = customerAddress;
		this.customerCity = customerCity;
		this.customerCountry = customerCountry;
		this.customerRegisterDate = customerRegisterDate;
		this.customerPassword = customerPassword;
	}

	public Customer(String customerEmail, String customerFullName, String customerAddress, String customerCity,
			String customerCountry, Date customerRegisterDate, String customerPassword, String customerPhone,
			Integer customerZipCode, Set<BookOrder> bookOrders) {
		this.customerEmail = customerEmail;
		this.customerFullName = customerFullName;
		this.customerAddress = customerAddress;
		this.customerCity = customerCity;
		this.customerCountry = customerCountry;
		this.customerRegisterDate = customerRegisterDate;
		this.customerPassword = customerPassword;
		this.customerPhone = customerPhone;
		this.customerZipCode = customerZipCode;
		this.bookOrders = bookOrders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CUSTOMER_ID", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CUSTOMER_EMAIL", nullable = false, length = 64)
	public String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	@Column(name = "CUSTOMER_FULL_NAME", nullable = false, length = 30)
	public String getCustomerFullName() {
		return this.customerFullName;
	}

	public void setCustomerFullName(String customerFullName) {
		this.customerFullName = customerFullName;
	}

	@Column(name = "CUSTOMER_ADDRESS", nullable = false, length = 128)
	public String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	@Column(name = "CUSTOMER_CITY", nullable = false, length = 32)
	public String getCustomerCity() {
		return this.customerCity;
	}

	public void setCustomerCity(String customerCity) {
		this.customerCity = customerCity;
	}

	@Column(name = "CUSTOMER_COUNTRY", nullable = false, length = 64)
	public String getCustomerCountry() {
		return this.customerCountry;
	}

	public void setCustomerCountry(String customerCountry) {
		this.customerCountry = customerCountry;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CUSTOMER_REGISTER_DATE", nullable = false, length = 19)
	public Date getCustomerRegisterDate() {
		return this.customerRegisterDate;
	}

	public void setCustomerRegisterDate(Date customerRegisterDate) {
		this.customerRegisterDate = customerRegisterDate;
	}

	@Column(name = "CUSTOMER_PASSWORD", nullable = false, length = 16)
	public String getCustomerPassword() {
		return this.customerPassword;
	}

	public void setCustomerPassword(String customerPassword) {
		this.customerPassword = customerPassword;
	}

	@Column(name = "CUSTOMER_PHONE", length = 10)
	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	@Column(name = "CUSTOMER_ZIP_CODE")
	public Integer getCustomerZipCode() {
		return this.customerZipCode;
	}

	public void setCustomerZipCode(Integer customerZipCode) {
		this.customerZipCode = customerZipCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<BookOrder> getBookOrders() {
		return this.bookOrders;
	}

	public void setBookOrders(Set<BookOrder> bookOrders) {
		this.bookOrders = bookOrders;
	}

}
